Api/Controllers/EmployeeWebController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

using Api.Models;
using Contracts.Database;
using Contracts.DTO;
using Contracts.Http;
using Domain.Commands;
using MediatR;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers
{
    public class EmployeeWebController : Controller
    {
        private readonly IMediator _mediator;
        private readonly int _perPage = 20;
        public EmployeeWebController(IMediator mediator)
        {
            _mediator = mediator;
        }

        public IActionResult Index(EmployeesViewModel employeesViewModel)
        {
            return View(employeesViewModel);
        }

        public async Task<IActionResult> Employees([FromQuery] int page = 1, CancellationToken cancellationToken = default)
        {
            GetAllEmployeesQuery query = new()
            {
                Page = page,
                PerPage = _perPage
            };

            GetAllEmployeesQueryResult result = await _mediator.Send(query, cancellationToken);

            GetFiltersQuery filtersQuery = new();
            GetFiltersQueryResult filtersResult = await _mediator.Send(filtersQuery, cancellationToken);

            BoundValues boundValues = new()
            {
                BoundFilterValues = filtersResult.BoundFilterValues,
                Departments = filtersResult.Departmens.ToList(),
                Positions = filtersResult.Positions.ToList()
            };

            EmployeesViewModel model = new()
            {
                Employees = result.Employees.ToList(),
                BoundValues = boundValues,
                Page = result.Page,
                PerPage = result.PerPage,
                PagesCount = result.PagesCount              
            };

            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> Employees([FromForm] EmployeesViewModel request, [FromQuery] int page = 1, CancellationToken cancellationToken = default)
        {
            GetFilteredEmployeesQuery query = new()
            {
                DepartmentId = request.Filters.DepartmentId,
                PositionId = request.Filters.PositionId,
                BoundFilterValues = request.Filters.BoundFilterValues,
                SearchRequest = request.Filters.SearchRequest,
                Page = page,
                PerPage = _perPage
            };

            GetFilteredEmployeesQueryResult result = await _mediator.Send(query, cancellationToken);

            GetFiltersQuery filtersQuery = new();
            GetFiltersQueryResult filtersResult = await _mediator.Send(filtersQuery, cancellationToken);

            BoundValues boundValues = new()
            {
                BoundFilterValues = filtersResult.BoundFilterValues,
                Departments = filtersResult.Departmens.ToList(),
                Positions = filtersResult.Positions.ToList()
            };

            EmployeesViewModel model = new()
            {
                Employees = result.Employees.ToList(),
                BoundValues = boundValues,
                Filters = request.Filters,
                Page = result.Page,
                PerPage = result.PerPage,
                PagesCount = result.PagesCount              
            };

            return View("Index", model);
        }

        public async Task<IActionResult> Edit(int id, CancellationToken cancellationToken = default)
        {
            GetEmployeeByIdQuery employeeByIdQuery = new() { Id = id };
            GetEmployeeByIdQueryResult employeeResult = await _mediator.Send(employeeByIdQuery, cancellationToken);

            if (!employeeResult.Success)
            {
                if (!employeeResult.EmployeeExists)
                {
                    ErrorResponse errorResponse = new()
                    {
                        Code = ErrorCode.EmployeeNotFound,
                        Message = "Employee does not exists"
                    };

                    return RedirectToAction("Error", "DepartmentsWeb", new { errorResponse });
                }
            }

            GetDepartmentsQuery departmentsQuery = new();
            GetDepartmentsQueryResult departmentsResult = await _mediator.Send(departmentsQuery, cancellationToken);

            GetPositionsQuery positionsQuery = new();
            GetPositionsQueryResult positionsResult = await _mediator.Send(positionsQuery, cancellationToken);

            EditEmployeeModel model = new()
            {
                Employee = employeeResult.Employee,
                AllDepartments = departmentsResult.Departments,
                AllPositions = positionsResult.Positions
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] Employee employee, int departmentId, int positionId, CancellationToken cancellationToken)
        {
            EditEmployeeCommand command = new()
            {
                Employee = employee,
                DepartmentId = departmentId,
                PositionId = positionId
            };
            
            EditEmployeeCommandResult result = await _mediator.Send(command, cancellationToken);

            if (!result.Success)
            {
                if (!result.EmployeeExists)
                {
                    ErrorResponse errorResponse = new()
                    {
                        Code = ErrorCode.EmployeeNotFound,
                        Message = "Employee does not exists"
                    };

                    return RedirectToAction("Error", "DepartmentsWeb", new { errorResponse });
                }

                if (!result.DepartmentExists)
                {
                    ErrorResponse errorResponse = new()
                    {
                        Code = ErrorCode.DepartmentNotFound,
                        Message = "Department does not exists"
                    };

                    return RedirectToAction("Error", "DepartmentsWeb", new { errorResponse });
                }

                if (!result.PositionExists)
                {
                    ErrorResponse errorResponse = new()
                    {
                        Code = ErrorCode.PositionNotFound,
                        Message = "Position does not exists"
                    };

                    return RedirectToAction("Error", "DepartmentsWeb", new { errorResponse });
                }
            }

            return RedirectToAction("Details", "DepartmentsWeb", new { departmentId });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(ErrorResponse errorResponse)
        {
            return View(new ErrorViewModel { ErrorCode = (int)errorResponse.Code / 100, Message = errorResponse.Message });
        }
    }
}

Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/employees-table.css" />
    <link rel="stylesheet" href="~/css/departments-table.css" />
    <link rel="stylesheet" href="~/css/department-details.css" />
    <link rel="stylesheet" href="~/css/edit-form.css" />
    <link rel="stylesheet" href="~/web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeWeb" asp-action="Employees">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DepartmentsWeb" asp-action="Departments">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>